### ISSUE TITLE
Some trailing slashes are not recognized

### ISSUE THREAD

**Issue by sobolevn** [vhf/remark-lint-no-url-trailing-slash#3]
I have faced a new issue (sorry for that).

For some reason it does not find all the slashes. For example (with the same old `aswesome-cryptography`'s `README.md`):

> [17:36:37] sobolev :: MacBook-Pro-Nikita  ➜  Documents/github/awesome-cryptography ‹master*› » npm test                                                     1 ↵
> 
> > awesome-cryptography@1.0.0 test /Users/sobolev/Documents/github/awesome-cryptography
> > ./node_modules/remark/bin/remark README.md CONTRIBUTING.md -f
> 
> README.md
>   80:3-80:41    warning  Remove trailing slash (https://www.crypto101.io)       trailing-slash
>   97:3-97:32    warning  Remove trailing slash (https://www.gnupg.org)          trailing-slash
>   103:3-103:39  warning  Remove trailing slash (http://www.cryptlib.com)        trailing-slash
>   106:3-106:33  warning  Remove trailing slash (https://nacl.cr.yp.to)          trailing-slash
>   114:3-114:43  warning  Remove trailing slash (http://bcrypt.sourceforge.net)  trailing-slash
>   115:3-115:40  warning  Remove trailing slash (https://botan.randombit.net)    trailing-slash
>   116:3-116:40  warning  Remove trailing slash (https://www.cryptopp.com)       trailing-slash
>   184:3-184:43  warning  Remove trailing slash (http://shiro.apache.org)        trailing-slash
>   217:3-217:39  warning  Remove trailing slash (http://www.paramiko.org)        trailing-slash
> 
> CONTRIBUTING.md: no issues found
> 
> ⚠ 9 warnings
> npm ERR! Test failed.  See above for more details. 

But that's obviously not true, since [https://github.com/sobolevn/awesome-cryptography/blame/master/README.md#L86](line 86) [https://github.com/sobolevn/awesome-cryptography/blame/master/README.md#L84](line 84) [https://github.com/sobolevn/awesome-cryptography/blame/master/README.md#L81](line 81) have the trailing slash, but are not listed.

A brief look at the code showed that the issue is somewhere here:

```
      var parsed = url.parse(nodeUrl);
      var target = parsed.protocol + '//' + parsed.host;

      if (nodeUrl === target + '/') { ... }
```

I will create a PR with the fix.

**Comment by vhf** [comment]
Thanks. What you are suggesting here is a bit different from what this package is intended to do.

A URL is always as follows: `scheme:[//[user:password@]host[:port]][/]path[?query][#fragment]` and this package warns about all URLs of the form `scheme://host/` because they could be written as ``scheme://host` instead.

The readme says:

> This rule checks that the host part of a URL has no extra trailing slash.

Now, `scheme://host` is _always_ equivalent to `scheme://host/`, so it's never a problem to prefer one over the other. This is not the case for `scheme://host/path` and `scheme://host/path/`.

Usually `scheme://host/path` and `scheme://host/path/` serve the same page on the web but there's no hard rule about this. These two could well be very different.

**Comment by vhf** [comment]
We could refactor your PR to add this behaviour using an option passed to this remark rule?

**Comment by sobolevn** [comment]
Oh, thanks for the explanation. I really did not figure it out earlier. 

What you suggest is creating a new option to check slashes at the end of any url, not only `scheme://host/`?

**Comment by vhf** [comment]
Yeah exactly. :)

Let's continue this discussion on the PR.
